import Image from "next/image";
import Hero from "./components/Hero";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="antialiased">
      <div className="w-full h-screen bg-cover bg-center bg-no-repeat relative content-end" style={{ backgroundImage: 'url(/pfHeroBg.png)' }}>
          <Hero />
          <Image width={1000} height={1000} alt="bglight" src={"/bg-light.png"} className="absolute left-8 h-screen w-auto" />
         </div>
        {children}
      </body>
    </html>
  );
}
